# ?? Datasource MySQL ????????????????????????????????????????????????
# ${DB_HOST:localhost} = utilise la variable DB_HOST, sinon "localhost"
# ${DB_NAME:miola}    = utilise la variable DB_NAME, sinon "miola"
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:miola}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ?? JPA / Hibernate ?????????????????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true

# ?? Serveur ?????????????????????????????????????????????????????????
server.port=8080

# ?? REST ????????????????????????????????????????????????????????????
spring.data.rest.base-path=/api