apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-crud-app
  template:
    metadata:
      labels:
        app: springboot-crud-app
    spec:
      containers:
        - name: springboot-crud-app
          image: springboot-crud-k8s:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:

            # ── Via ConfigMap (données non sensibles) ─────────────────
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:         # Référence au ConfigMap
                  name: mysql-config       # Nom du ConfigMap
                  key: host                # Clé dans le ConfigMap (host: mysql)

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: dbName               # Clé "dbName: miola"

            # ── Via Secret (données sensibles) ────────────────────────
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:             # Référence au Secret
                  name: mysql-secret       # Nom du Secret
                  key: username             # Clé "username" dans le Secret

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password             # Clé "password" dans le Secret

---

apiVersion: v1
kind: Service
metadata:
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-crud-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008