apiVersion: v1
kind: Secret                    # Type : données sensibles encodées
metadata:
  name: mysql-secret            # Nom référencé dans app-deployment.yaml
type: Opaque                    # Type générique pour les données arbitraires
data:                            # Valeurs encodées en Base64 (PAS en clair !)
  username: cm9vdA==            # "root" encodé en Base64
  password: TmlmbzIzTGlmbzA1  # "Nifo23Lifo05" encodé en Base64